name: flutter_sample_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_native_splash: ^2.2.6
  freezed: ^2.1.0+1
  gap: ^2.0.0
  hooks_riverpod: ^1.0.4

dev_dependencies:
  build_runner: ^2.2.0
  flutter_gen_runner:
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.19.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true

flutter_native_splash:
  color: '#FFFFFF'
  image: 'assets/splash_icons/icon.png'
  fullscreen: true

  # android_12:
  #   icon_background_color: '#fff'
  #   image: 'assets/images/splash_android12.png'

flutter_gen:
  output: lib/gen/
  colors:
    inputs:
      - assets/color/colors.xml

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
