name: flutter_sample_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  adaptive_dialog: ^1.8.0
  cached_network_image: ^3.2.1
  connectivity_plus: ^2.3.6
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  font_awesome_flutter: ^10.1.0
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  gap: ^2.0.0
  geolocator: ^9.0.1
  hooks_riverpod: ^1.0.4
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  settings_ui: ^2.0.2
  shared_preferences: ^2.0.15
  simple_logger: ^1.9.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_gen_runner:
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.6
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.19.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: YuseiMagic
      fonts:
        - asset: assets/fonts/YuseiMagic-Regular.ttf

flutter_icons:
  android: true
  ios: true

flutter_native_splash:
  color: '#FFFFFF'
  image: 'assets/splash_icons/icon.png'
  fullscreen: true

  # android_12:
  #   icon_background_color: '#fff'
  #   image: 'assets/images/splash_android12.png'

flutter_gen:
  output: lib/utils/gen/
  colors:
    inputs:
      - assets/color/colors.xml
